"""Regenerate figures for the MAT-STK2011 report.

Produces:

    fig_sim_attenuation.pdf  - naive GLM attenuation across the full eps range
                               (the naive fit has no bound, so it is generated here)

The corrected-MLE figures (fig_sim_corrected, fig_sim_sd_growth, fig_breast_paths,
fig_breast_overlay, fig_breast_pvalues) used to be generated by this script with a
post-hoc bound-hit filter (replicates with |beta_j_hat| at the bound were dropped).
That filter contradicted what the report says it does: Definition 3.4 promises that
no replicate is removed from MC-sd / coefficient-path summaries. Those figures are
now produced exclusively by generate_unfiltered_figures.py, which keeps every
replicate (bound-hits are plotted as triangles at +/- M instead of being dropped).

If you change the simulation grid here (A_TRUE, B_TRUE, N_B, B_MC, EPS_GRID), keep
the corresponding constants in generate_unfiltered_figures.py in sync.
"""

from pathlib import Path
import sys
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from scipy.optimize import minimize
from scipy.special import expit
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

# ---- styling (re-use the project helper) ----
HERE = Path(__file__).resolve().parent
sys.path.append(str(HERE))
from helper_functions.styling import set_latex_plot_style, save_latex_figure
from helper_functions.corrected_mle import SEED  # 6114, used everywhere

set_latex_plot_style(use_tex=False, figure_size=(6.0, 3.6))

# Figures land next to the LaTeX source: ../MAT-STK2011-Project/figures.
# Falls back to a local figures/ dir if the report directory does not exist
# (e.g. running the script in isolation).
PROJECT_FIG_DIR = (HERE.parent / "MAT-STK2011-Project" / "figures").resolve()
LOCAL_FIG_DIR = (HERE / "figures").resolve()
OUT = PROJECT_FIG_DIR if PROJECT_FIG_DIR.parent.exists() else LOCAL_FIG_DIR
OUT.mkdir(parents=True, exist_ok=True)
print(f"Figures will be saved to: {OUT}")


# ========== keep-strip helpers ==========
# Every corrected-fit figure attaches a thin strip at the bottom that shows,
# for each epsilon on the x-axis, the fraction of Monte-Carlo replicates that
# survived the L-BFGS-B bound check. This makes clear what was dropped before
# the MC summary statistics were computed.

from matplotlib.gridspec import GridSpec

def _keep_fraction(samples):
    """Per-ε fraction of replicates retained (NaN == dropped)."""
    arr = samples if samples.ndim == 2 else samples[..., 0]
    return (~np.isnan(arr)).mean(axis=1)


def _fig_with_strip(n_rows_main=1, n_cols=1, figsize=None,
                    keep_frac_height=0.18, hspace=None):
    """Build a figure with an extra strip-row at the bottom spanning all cols.

    When `n_rows_main >= 2`, xtick labels are hidden on the upper main rows so
    they do not crash into the titles of the row below.
    """
    if figsize is None:
        figsize = (3.8 * n_cols, 3.0 * n_rows_main + 1.0)
    if hspace is None:
        hspace = 0.45 if n_rows_main >= 2 else 0.28
    fig = plt.figure(figsize=figsize)
    gs = GridSpec(n_rows_main + 1, n_cols, figure=fig,
                  height_ratios=[1.0] * n_rows_main + [keep_frac_height * n_rows_main],
                  hspace=hspace)
    main_axes = np.empty((n_rows_main, n_cols), dtype=object)
    for r in range(n_rows_main):
        for c in range(n_cols):
            main_axes[r, c] = fig.add_subplot(gs[r, c])
    strip_ax = fig.add_subplot(gs[n_rows_main, :])
    # Hide xtick labels on the upper main rows so they cannot collide with the
    # titles of the row beneath. The bottom main row keeps its ticks.
    if n_rows_main >= 2:
        for r in range(n_rows_main - 1):
            for c in range(n_cols):
                plt.setp(main_axes[r, c].get_xticklabels(), visible=False)
    return fig, main_axes, strip_ax


def _draw_keep_strip(ax, grid, keep_frac):
    w = float(np.diff(grid).min()) * 0.7 if len(grid) > 1 else 0.02
    colors = [(0.65 - 0.45 * k, 0.65 - 0.45 * k, 0.75 - 0.45 * k, 0.85)
              for k in keep_frac]
    ax.bar(grid, keep_frac, width=w, color=colors, edgecolor='black', linewidth=0.3)
    ax.axhline(1.0, color='grey', lw=0.4, ls=':')
    ax.set_ylim(0, 1.08)
    ax.set_yticks([0.0, 0.5, 1.0])
    ax.set_yticklabels(['0', '.5', '1'])
    ax.set_ylabel('kept', fontsize=8)
    ax.set_xlabel(r'$\varepsilon = \delta$')
    ax.grid(axis='y', alpha=0.25, lw=0.4)
    for x, k in zip(grid, keep_frac):
        if k < 0.5:
            ax.text(x, k + 0.04, f"{k:.0%}", ha='center', va='bottom',
                    fontsize=6, color='firebrick')
    ax.set_title('fraction of MC replicates retained after the bound check',
                 fontsize=8, loc='left', pad=2)


# ========== helpers (same as in the notebooks) ==========
def H(u): return expit(u)

def simulate_ab(n, a, b, eps, delta, rng):
    x = rng.standard_normal(n)
    p = H(a + b * x)
    y = rng.binomial(1, p)
    flip1 = (y == 1) & (rng.uniform(size=n) < eps)
    flip0 = (y == 0) & (rng.uniform(size=n) < delta)
    yh = y.copy()
    yh[flip1] = 0
    yh[flip0] = 1
    return x, y, yh

def fit_naive(X, y):
    Xd = sm.add_constant(X, has_constant='add')
    try:
        r = sm.GLM(y, Xd, family=sm.families.Binomial()).fit(disp=0)
        return np.asarray(r.params), np.asarray(r.bse)
    except Exception:
        k = Xd.shape[1]
        return np.full(k, np.nan), np.full(k, np.nan)

def neg_logL(theta, Xd, yh, eps, delta):
    eta = Xd @ theta
    p = H(eta)
    c = 1.0 - eps - delta
    ps = np.clip(delta + c * p, 1e-12, 1 - 1e-12)
    return -np.sum(yh * np.log(ps) + (1 - yh) * np.log(1 - ps))

def grad_L(theta, Xd, yh, eps, delta):
    eta = Xd @ theta
    p = H(eta)
    c = 1.0 - eps - delta
    ps = np.clip(delta + c * p, 1e-12, 1 - 1e-12)
    w = c * p * (1.0 - p)
    r = (yh - ps) / (ps * (1.0 - ps))
    return -Xd.T @ (r * w)

def fit_corr(X, yh, eps, delta, start, bounded=False, bound=15.0):
    Xd = sm.add_constant(X, has_constant='add')
    if bounded:
        bnds = [(-bound, bound)] * len(start)
        return minimize(neg_logL, x0=start, args=(Xd, yh, eps, delta),
                        jac=grad_L, method='L-BFGS-B', bounds=bnds)
    return minimize(neg_logL, x0=start, args=(Xd, yh, eps, delta),
                    jac=grad_L, method='BFGS')

def numeric_hess(f, theta, h=1e-4):
    d = len(theta)
    Hm = np.zeros((d, d))
    for i in range(d):
        for j in range(i, d):
            tp  = theta.copy(); tp[i]  += h; tp[j]  += h
            tm  = theta.copy(); tm[i]  -= h; tm[j]  -= h
            tpm = theta.copy(); tpm[i] += h; tpm[j] -= h
            tmp = theta.copy(); tmp[i] -= h; tmp[j] += h
            v = (f(tp) - f(tpm) - f(tmp) + f(tm)) / (4 * h * h)
            Hm[i, j] = v; Hm[j, i] = v
    return Hm

def se_hess(theta, X, yh, eps, delta):
    Xd = sm.add_constant(X, has_constant='add')
    J = numeric_hess(lambda t: neg_logL(t, Xd, yh, eps, delta), theta)
    try:
        cov = np.linalg.inv(J)
    except np.linalg.LinAlgError:
        return np.full(len(theta), np.nan)
    diag = np.diag(cov)
    return np.where(diag > 0, np.sqrt(np.abs(diag)), np.nan)


# ========== TASK (b) SIMULATION ==========

A_TRUE, B_TRUE = 0.5, 1.2
N_B = 1000
B_MC = 120
EPS_GRID = np.concatenate([np.linspace(0.0, 0.48, 13),
                           np.linspace(0.52, 0.99, 13)])

naive_a = np.full((len(EPS_GRID), B_MC), np.nan)
naive_b = np.full((len(EPS_GRID), B_MC), np.nan)
corr_a  = np.full((len(EPS_GRID), B_MC), np.nan)
corr_b  = np.full((len(EPS_GRID), B_MC), np.nan)
corr_a_se = np.full((len(EPS_GRID), B_MC), np.nan)
corr_b_se = np.full((len(EPS_GRID), B_MC), np.nan)

SIM_BOUND = 10.0  # the corrected likelihood is flat in beta when c = 1-eps-delta
                  # is small; bound the optimizer so BFGS cannot wander to infinity
                  # and drop replicates that hit the boundary as non-identified.

rng_mc = np.random.default_rng(SEED)
for k, eps in enumerate(EPS_GRID):
    for b in range(B_MC):
        x, y, yh = simulate_ab(N_B, A_TRUE, B_TRUE, eps, eps, rng_mc)
        ab_n, _ = fit_naive(x.reshape(-1, 1), yh)
        if np.any(np.isnan(ab_n)):
            continue
        naive_a[k, b] = ab_n[0]; naive_b[k, b] = ab_n[1]
        start = ab_n.copy() if eps < 0.5 else -ab_n.copy()
        rc = fit_corr(x.reshape(-1, 1), yh, eps, eps, start,
                      bounded=True, bound=SIM_BOUND)
        if np.max(np.abs(rc.x)) >= SIM_BOUND - 0.1:
            continue  # non-identified replicate
        corr_a[k, b] = rc.x[0]; corr_b[k, b] = rc.x[1]
        se = se_hess(rc.x, x.reshape(-1, 1), yh, eps, eps)
        corr_a_se[k, b] = se[0]; corr_b_se[k, b] = se[1]

print("task-b MC done; overall convergent fraction = %.3f"
      % np.mean(~np.isnan(corr_a)))


# ---- Figure 1: naive attenuation ----
def _panel(ax, grid, samples, true_val, color):
    m = np.nanmean(samples, axis=1)
    s = np.nanstd(samples, axis=1, ddof=1)
    jit = np.random.default_rng(0).standard_normal(samples.shape) * 0.003
    xx = grid[:, None] + jit
    ax.plot(xx.ravel(), samples.ravel(), '.', ms=1.8, alpha=0.12, color=color)
    ax.fill_between(grid, m - s, m + s, alpha=0.22, color=color)
    ax.plot(grid, m, 'o-', color=color, ms=3.0, lw=1.1)
    ax.axhline(true_val, color='k', ls=':', lw=0.9)
    ax.axhline(0, color='grey', lw=0.4)
    ax.axvline(0.5, color='r', ls='--', lw=0.7, alpha=0.5)

fig, axes = plt.subplots(1, 2, figsize=(10, 3.4))
_panel(axes[0], EPS_GRID, naive_a, A_TRUE, 'tab:blue')
axes[0].set_xlabel(r'$\varepsilon = \delta$')
axes[0].set_ylabel(r'$\widehat{\beta}_0$')
axes[0].set_title('Naive GLM intercept')
_panel(axes[1], EPS_GRID, naive_b, B_TRUE, 'tab:orange')
axes[1].set_xlabel(r'$\varepsilon = \delta$')
axes[1].set_ylabel(r'$\widehat{\beta}_1$')
axes[1].set_title('Naive GLM slope')
plt.tight_layout()
save_latex_figure(str(OUT / 'fig_sim_attenuation.pdf'))
plt.close()




print("\nAll figures saved to", OUT)
for p in sorted(OUT.glob('*.pdf')):
    print(" ", p.name, p.stat().st_size, 'bytes')
