import numpy as np


def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))


def generate_toy_logistic_data(
    n=1000,
    p=3,
    beta_true=None,
    x_corr=0.0,
    noise_level=0.1,
    seed=None
):
    """
    Generate a toy binary classification dataset with symmetric label noise.

    True labels are generated from a logistic regression model.
    Observed labels are generated by flipping true labels with probability noise_level.

    Parameters
    ----------
    n : int
        Number of observations
    p : int
        Number of predictors
    beta_true : array-like, shape (p,)
        True regression coefficients
    x_corr : float in [0,1)
        Correlation between predictors (AR(1)-style)
    noise_level : float in [0,1]
        Probability that a label is flipped
    seed : int or None
        Random seed

    Returns
    -------
    dict with keys:
        X        : (n, p) predictors
        y_true   : (n,) true labels
        y_noisy  : (n,) noisy/observed labels
        p_true   : (n,) true probabilities
        beta_true: (p,) true coefficients
        flip_mask: (n,) boolean, True if label was flipped
    """

    rng = np.random.default_rng(seed)

    # --- coefficients ---
    if beta_true is None:
        beta_true = np.linspace(1.0, -0.5, p)
    beta_true = np.asarray(beta_true, dtype=float)

    # --- predictors ---
    cov = x_corr ** np.abs(np.subtract.outer(np.arange(p), np.arange(p)))
    X = rng.multivariate_normal(mean=np.zeros(p), cov=cov, size=n)

    # --- true logistic model ---
    linear_pred = X @ beta_true
    p_true = sigmoid(linear_pred)
    y_true = rng.binomial(1, p_true)

    # --- symmetric label noise ---
    flip_mask = rng.uniform(0.0, 1.0, size=n) < noise_level
    y_noisy = y_true.copy()
    y_noisy[flip_mask] = 1 - y_noisy[flip_mask]

    return {
        "X": X,
        "y_true": y_true,
        "y_noisy": y_noisy,
        "p_true": p_true,
        "beta_true": beta_true,
        "flip_mask": flip_mask,
    }
